version: 1.0
provider:
  name: openfaas
  gateway: http://127.0.0.1:8080

functions:
  publisher:
    lang: golang-http
    handler: ./publisher
    image: publisher:latest
  quoter:
    lang: golang-middleware
    handler: ./quoter
    image: quoter:latest

  jules:
    lang: golang-middleware
    handler: ./jules
    image: jules:latest
    build_args:
      GO111MODULE: off
      GOFLAGS: "-mod=vendor"
